### ISSUE TITLE
is it possible to unmap bindings?

### ISSUE THREAD

**Issue by molleweide** [lazytanuki/nvim-mapper#16]
Hi,

Is it possibl to unmap already existing bindings with nvim mapper?

**Comment by Normanras** [comment]
Are you talking about default bindings or bindings you've setup and defined in a `keymaps.lua` (or similar) file?

I ask because I imagine if you convert your original key mapping definition to the syntax and format used by `nvim-mapper` wouldn't that unbind (and then rebind) the existing mappings? Can you not just delete the mappings you've already setup?

**Comment by molleweide** [comment]
Hi, it was a while agon since i posted and I am not sure what my goal was.

Thx for replying in any case :)

Ill close.
